name: detekt

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - feature/automation-metrics

jobs:
  detekt:
    name: Run Detekt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Run detekt
        run: |
          ./gradlew :app:detekt --no-daemon --console=plain

      - name: Upload detekt report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: detekt-report
          path: app/build/reports/detekt
