name: Project Metrics

on:
  schedule:
    - cron: '0 6 * * MON' # Every Monday 06:00 UTC
  workflow_dispatch:

jobs:
  generate-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
      issues: read
      pull-requests: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gather metrics and write report
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const { owner, repo } = context.repo;
            const sinceDays = 30;
            const since = new Date(Date.now() - sinceDays * 24 * 60 * 60 * 1000).toISOString();

            // Helper: list PRs updated since
            const prs = await github.rest.pulls.list({ owner, repo, state: 'open', per_page: 100 });
            const openPrs = prs.data;

            const openPrAgeBuckets = { '<=7':0, '<=14':0, '<=30':0, '>30':0 };
            const now = Date.now();
            for (const pr of openPrs) {
              const ageDays = Math.floor((now - new Date(pr.created_at).getTime()) / (24*60*60*1000));
              if (ageDays <=7) openPrAgeBuckets['<=7']++;
              else if (ageDays <=14) openPrAgeBuckets['<=14']++;
              else if (ageDays <=30) openPrAgeBuckets['<=30']++;
              else openPrAgeBuckets['>30']++;
            }

            // Mean time to merge over merged PRs in the last 30 days
            const mergedPrs = await github.paginate(github.rest.pulls.list, { owner, repo, state: 'closed', per_page: 100 });
            const recentMerged = mergedPrs.filter(p => p.merged_at && new Date(p.merged_at) >= new Date(since));
            let totalMergeMs = 0;
            for (const p of recentMerged) totalMergeMs += (new Date(p.merged_at) - new Date(p.created_at));
            const meanTimeToMergeDays = recentMerged.length ? (totalMergeMs / recentMerged.length) / (24*60*60*1000) : 0;

            // CI pass rate: check workflow runs in last 30 days
            const runs = await github.paginate(github.rest.actions.listWorkflowRunsForRepo, { owner, repo, per_page: 100 });
            const recentRuns = runs.filter(r => new Date(r.created_at) >= new Date(since));
            const succeeded = recentRuns.filter(r => r.conclusion === 'success').length;
            const passRate = recentRuns.length ? Math.round((succeeded / recentRuns.length) * 100) : 0;

            // Open issues by age
            const issuesRes = await github.paginate(github.rest.issues.listForRepo, { owner, repo, state: 'open', per_page: 100 });
            const issues = issuesRes.filter(i => !i.pull_request);
            const issueAgeBuckets = { '<=7':0, '<=14':0, '<=30':0, '>30':0 };
            for (const issue of issues) {
              const ageDays = Math.floor((now - new Date(issue.created_at).getTime()) / (24*60*60*1000));
              if (ageDays <=7) issueAgeBuckets['<=7']++;
              else if (ageDays <=14) issueAgeBuckets['<=14']++;
              else if (ageDays <=30) issueAgeBuckets['<=30']++;
              else issueAgeBuckets['>30']++;
            }

            // Build markdown
            const md = [];
            md.push('# Project Metrics');
            md.push('Generated: ' + new Date().toISOString());
            md.push('');
            md.push('## Pull Requests');
            md.push(`Open PRs: ${openPrs.length}`);
            md.push('');
            md.push('Open PRs by age:');
            md.push(`- <= 7 days: ${openPrAgeBuckets['<=7']}`);
            md.push(`- <= 14 days: ${openPrAgeBuckets['<=14']}`);
            md.push(`- <= 30 days: ${openPrAgeBuckets['<=30']}`);
            md.push(`- > 30 days: ${openPrAgeBuckets['>30']}`);
            md.push('');
            md.push('## Merge Metrics');
            md.push(`Mean time to merge (last ${sinceDays} days): ${meanTimeToMergeDays.toFixed(2)} days`);
            md.push('');
            md.push('## CI Metrics');
            md.push(`Workflow runs (last ${sinceDays} days): ${recentRuns.length}`);
            md.push(`Pass rate: ${passRate}%`);
            md.push('');
            md.push('## Issues');
            md.push(`Open issues: ${issues.length}`);
            md.push('Open issues by age:');
            md.push(`- <= 7 days: ${issueAgeBuckets['<=7']}`);
            md.push(`- <= 14 days: ${issueAgeBuckets['<=14']}`);
            md.push(`- <= 30 days: ${issueAgeBuckets['<=30']}`);
            md.push(`- > 30 days: ${issueAgeBuckets['>30']}`);

            const content = md.join('\n');

            // Write file to reports/project-metrics.md (create folder if needed)
            const path = 'reports/project-metrics.md';
            const enc = Buffer.from(content).toString('base64');

            try {
              // Check if file exists
              const existing = await github.rest.repos.getContent({ owner, repo, path });
              // Update
              await github.rest.repos.createOrUpdateFileContents({
                owner, repo, path, message: 'chore(reports): update project metrics', content: enc, sha: existing.data.sha
              });
            } catch (err) {
              // Create new
              await github.rest.repos.createOrUpdateFileContents({
                owner, repo, path, message: 'chore(reports): add project metrics', content: enc
              });
            }

            core.info('Project metrics generated and committed to ' + path);

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: project-metrics
          path: reports/project-metrics.md
